CONFIG_ANT=y
CONFIG_ANT_LIBRARY_CORE=y
CONFIG_ANT_COMMON=y
CONFIG_ANT_KEY_MANAGER=y
CONFIG_ANT_CHANNEL_CONFIG=y
CONFIG_ANT_SDC_INIT=y
CONFIG_ANT_EVALUATION_KEY=y
CONFIG_ANT_TOTAL_CHANNELS_ALLOCATED=3
