#pragma once

enum ant_battery_status_t {
  ANT_BATTERY_STATUS_NEW = 1,
  ANT_BATTERY_STATUS_GOOD = 2,
  ANT_BATTERY_STATUS_OK = 3,
  ANT_BATTERY_STATUS_LOW = 4,
  ANT_BATTERY_STATUS_CRITICAL = 5,
  ANT_BATTERY_STATUS_INVALID = 7,
};